version: 0.2

env:
  variables:
    MyEnv: "dev"
    MyAccountId: "548616401217"
    MyRegion: "us-east-1"

phases:
  install:
    runtime-versions:
      python: latest
    commands:
      # Install the AWS CLI and SAM CLI
      - pip3 install awscli aws-sam-cli
     #- pip install boto3
     #- sam --version

  build:
    commands:
     # - sam validate --template template.yml
      - sam build --use-container -t template.yml
      
     #- aws ecr get-login-password --region $MyRegion | docker login --username AWS --password-stdin $MyAccountId.dkr.ecr.us-east-1.amazonaws.com 
     #- aws s3 sync resources s3://sam-cli-dionysus-bucket/resources/ --delete

  post_build:
    commands:
      - sam deploy --stack-name sam-app --resolve-s3 --capabilities CAPABILITY_IAM --resolve-image-repos
      
      #- sam package --template-file template.yml --s3-bucket sam-cli-dionysus-bucket --output-template-file packaged.yml 
      #- sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --template-file packaged.yml --stack-name $MyEnv-dionysus-stack --parameter-overrides Env=$MyEnv AccountId=$MyAccountId Region=$MyRegion --capabilities CAPABILITY_IAM CAPABILITY_AUTO_EXPAND 
