version: 0.2

phases:
  build:
    commands:
      - sam build -t template.yml

  post_build:
    commands:
      - |
        sam deploy --no-confirm-changeset --no-fail-on-empty-changeset \
        --s3-bucket sam-cli-test-v1 \
        --s3-prefix dev \
        --region us-west-1 \
        --stack-name sam-test-v1\
        --capabilities CAPABILITY_IAM \
        --parameter-overrides \
        Environment=dev
