AWSTemplateFormatVersion: '2010-09-09'
#Transform: AWS::Serverless-2016-10-31
Parameters:
  Region:
    Type: String
    #Default: us-west-1
    Description: The AWS region in which to create resources.

  AccountId:
    Type: String
    #Default: 548616401217
    Description: The AWS account ID where the resources will be created.
      
  Env:
    Type: String
    #Default: dev
    Description: Environment name.

Resources:
  LambdaStack1:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./myfolder1/test1.yml
      Parameters:
        Region: !Ref Region
        AccountId: !Ref AccountId
        Env: !Ref Env
  
  LambdaStack2:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./myfolder2/test2.yml
      Parameters:
        Region: !Ref Region
        AccountId: !Ref AccountId
        Env: !Ref Env
        
        
  MyRestApi1:
    Type: 'AWS::ApiGateway::RestApi'
    Properties:
      Name: !Sub '${Env}_test_api'
      EndpointConfiguration:
        Types:
          - REGIONAL
          
  ResourceStack1:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./hello_world/test3.yml
      Parameters:
        RestApiId: !Ref MyRestApi1
        Region: !Ref Region
        AccountId: !Ref AccountId
        Env: !Ref Env
        MyLambdaFunctionName1: !GetAtt LambdaStack1.Outputs.MyLambdaFunction1Name
        MyLambdaFunctionArn1: !GetAtt LambdaStack1.Outputs.MyLambdaFunction1Arn
      Outputs:
        Resource1Id:
          Value: !GetAtt Resource1.ResourceId

  ResourceStack2:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./hello_world/test4.yml
      Parameters:
        RestApiId: !Ref MyRestApi1
        Region: !Ref Region
        AccountId: !Ref AccountId
        Env: !Ref Env   
        MyLambdaFunctionName2: !GetAtt LambdaStack2.Outputs.MyLambdaFunction2Name
        MyLambdaFunctionArn2: !GetAtt LambdaStack2.Outputs.MyLambdaFunction2Arn
      Outputs:
        Resource2Id:
          Value: !GetAtt Resource2.ResourceId

    
