AWSTemplateFormatVersion: '2010-09-09'
#Transform: AWS::Serverless-2016-10-31
Parameters:
  Region:
    Type: String
    #Default: us-west-1
    Description: The AWS region in which to create resources.

  AccountId:
    Type: String
    #Default: 548616401217
    Description: The AWS account ID where the resources will be created.
      
  Env:
    Type: String
    #Default: dev
    Description: Environment name.
    
  LambdaFunctionArn1:
    Type: String
    #Default: dev
    Description: LambdaFunction name.
   

Resources:
  LambdaStack1:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./myfolder1/test1.yml
      Parameters:
        Region: !Ref Region
        AccountId: !Ref AccountId
        Env: !Ref Env

  ApiGatewayStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./hello_world/test3.yml
      Parameters:
        Region: !Ref Region
        AccountId: !Ref AccountId
        Env: !Ref Env
        LambdaFunctionArn1: !GetAtt LambdaStack1.Outputs.MyLambdaFunction1Arn # Pass the Lambda function's ARN as a parameter
    
