AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  Region:
    Type: String
    #Default: 'us-east-1'
    Description: The AWS region in which to create resources

  AccountId:
    Type: String
    #Default: '548616401217'
    Description: The AWS account ID where the resources will be created.
      
  Env:
    Type: String
    #Default: 'devops'
    Description: Environment name.
Resources:
  HelloWorldAPI:
    Type: AWS::Serverless::Api
    Properties:
      Name: Hello World API
      StageName: Prod
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      ImageConfig:
        Command: ["helo_world/lambda_function.lambda_handler"]
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref HelloWorldAPI
            Path: /hello
            Method: get
    Metadata:
      Dockerfile: hello_world/Dockerfile
      DockerContext: .
      DockerTag: v1
