AWSTemplateFormatVersion: '2010-09-09'
#Transform: 'AWS::Serverless-2016-10-31'
Parameters:
  Region:
    Type: String
    #Default: 'us-east-1'
    Description: The AWS region in which to create resources

  AccountId:
    Type: String
    #Default: '548616401217'
    Description: The AWS account ID where the resources will be created.
      
  Env:
    Type: String
    #Default: 'devops'
    Description: Environment name.
    
  MyRestApiId:
    Type: String
    #Default: 'devops'
    Description: RestApi Id.
   
  MyLambdaFunctionName2:
    Type: String
    #Default: dev
    Description: LambdaFunction name.
    
  MyLambdaFunctionArn2:
    Type: String
    #Default: dev
    Description: LambdaFunction Arn.
    
Resources:

  MyResource2:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      RestApiId: !Ref MyRestApiId
      ParentId: !GetAtt MyRestApiId:RootResourceId
      PathPart: 'test2'

  MyMethod2:
    Type: 'AWS::ApiGateway::Method'
    Properties:
      RestApiId: !Ref MyRestApiId
      ResourceId: !Ref MyResource2
      HttpMethod: GET
      AuthorizationType: NONE #COGNITO_USER_POOLS  # Set authorization type to COGNITO_USER_POOLS
     # AuthorizerId: !Ref MyAuthorizer  # Set the ID of the authorizer
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 'arn:aws:apigateway:${Region}:lambda:path/2015-03-31/functions/${MyLambdaFunctionArn2}/invocations'
   
   
  MyAuthorizer:
    Type: 'AWS::ApiGateway::Authorizer'
    Properties:
      Name: my-cognito-authorizer
      Type: COGNITO_USER_POOLS
      IdentitySource: method.request.header.Authorization
      RestApiId: !Ref MyRestApiId
      ProviderARNs:
        - !Sub arn:aws:cognito-idp:${Region}:${AccountId}:userpool/us-east-1_zHG6ezXPp    #${UserPoolId}

  MyDeployment:
    Type: 'AWS::ApiGateway::Deployment'
    DependsOn:
          - MyMethod2 
    Properties:
      RestApiId: !Ref MyRestApiId

  MyStage:
    Type: 'AWS::ApiGateway::Stage'
    Properties:
      RestApiId: !Ref MyRestApiId
      DeploymentId: !Ref MyDeployment
      StageName: !Sub '${Env}'
      Variables:
        env: !Sub '${Env}'
   
  MyLambdaPermission2:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !Sub  ${MyLambdaFunctionName2}
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:${Region}:${AccountId}:${MyRestApiId}/${Env}/GET/test2'
      
